[package]
name = "mycode-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints.rust]
warnings = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
unwrap_used = "deny"

[dependencies]
base64.workspace = true
mycode-plugin-protocol = { path = "../mycode-plugin-protocol" }
clap.workspace = true
crossterm.workspace = true
nix.workspace = true
ratatui.workspace = true
reqwest.workspace = true
futures-util.workspace = true
tokio-util.workspace = true
serde.workspace = true
serde_json.workspace = true
textwrap.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
